export const movies = [
    {
        id: 1,
        title: "The Shawshank Redemption",
        year: 1994,
        genre: "Drama",
        rating: 9.3,
        poster: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
        director: "Frank Darabont",
        musicDirector: "Thomas Newman",
        synopsis: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        numberOfReviews: 2000
    },
    {
        id: 2,
        title: "The Godfather",
        year: 1972,
        genre: "Crime, Drama",
        rating: 9.2,
        poster: "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        cast: ["Marlon Brando", "Al Pacino", "James Caan"],
        director: "Francis Ford Coppola",
        musicDirector: "Nino Rota",
        synopsis: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        numberOfReviews: 1800
    },
    {
        id: 3,
        title: "The Dark Knight",
        year: 2008, 
        genre: "Action, Crime, Drama",
        rating: 9.0,
        poster: "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        director: "Christopher Nolan",
        musicDirector: "Hans Zimmer",
        synopsis: "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        numberOfReviews: 2500
    },
    {
        id: 4,
        title: "Inception",
        year: 2010,
        genre: "Action, Adventure, Sci-Fi",
        rating: 8.8,
        poster: "https://image.tmdb.org/t/p/original/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
        director: "Christopher Nolan",
        musicDirector: "Hans Zimmer",
        synopsis: "Cobb steals information from his targets by entering their dreams.",
        numberOfReviews: 2200
    },
    {
        id: 5,
        title: "The Lord of the Rings: The Return of the King",
        year: 2003,
        genre: "Adventure, Drama, Fantasy",
        rating: 8.9,
        poster: "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg",
        cast: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
        director: "Peter Jackson",
        musicDirector: "Howard Shore",
        synopsis: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
        numberOfReviews: 3000
    },
    {
        id: 6,
        title: "The Shawshank Redemption",
        year: 1994,
        genre: "Drama",
        rating: 9.3,
        poster: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
        director: "Frank Darabont",
        musicDirector: "Thomas Newman",
        synopsis: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        numberOfReviews: 2000
    },
    {
        id: 7,
        title: "The Godfather",
        year: 1972,
        genre: "Crime, Drama",
        rating: 9.2,
        poster: "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        cast: ["Marlon Brando", "Al Pacino", "James Caan"],
        director: "Francis Ford Coppola",
        musicDirector: "Nino Rota",
        synopsis: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        numberOfReviews: 1800
    },
    {
        id: 8,
        title: "The Dark Knight",
        year: 2008, 
        genre: "Action, Crime, Drama",
        rating: 9.0,
        poster: "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        director: "Christopher Nolan",
        musicDirector: "Hans Zimmer",
        synopsis: "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        numberOfReviews: 2500
    },
    {
        id: 9,
        title: "Inception",
        year: 2010,
        genre: "Action, Adventure, Sci-Fi",
        rating: 8.8,
        poster: "https://image.tmdb.org/t/p/original/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
        director: "Christopher Nolan",
        musicDirector: "Hans Zimmer",
        synopsis: "Cobb steals information from his targets by entering their dreams.",
        numberOfReviews: 2200
    }
]